AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template with Lambda and DynamoDB

Globals:
  Function:
    Timeout: 10
    Runtime: python3.13
    MemorySize: 128

Resources:

  ###############################
  # LAYERS
  ###############################
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MySimpleApi
      StageName: prod
      Auth:
        DefaultAuthorizer: NONE

  ###############################
  # LAYERS
  ###############################
  MyLib:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mylib
      ContentUri: ../layers/mylib/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

  ###############################
  # API LAMBDA
  ###############################
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api-lambda/src/
      Handler: api_lambda.main.handler
      Layers:
        - !Ref MyLib
      Policies:
        - DynamoDBCrudPolicy:
            TableName: MyTable
      Environment:
        Variables:
          TABLE_NAME: MyTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: "/{proxy+}"  # does not match root path
            Method: ANY
            RestApiId: !Ref MyApi
            Auth:
              Authorizer: NONE

  ###############################
  # DYNAMODB TABLE
  ###############################
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
