---

- name: Ensure files are created with correct permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    modification_time: preserve
    access_time: preserve
  loop:
    - /etc/pve/local/pveproxy-ssl.pem
    - /etc/pve/local/pveproxy-ssl.key

- name: Ensure certificate is present
  ansible.builtin.copy:
    dest: "/etc/pve/local/pveproxy-ssl.pem"
    content: "{{ ssl_cert }}"
  notify: Restart pveproxy

- name: Ensure private key is present
  ansible.builtin.copy:
    dest: "/etc/pve/local/pveproxy-ssl.key"
    content: "{{ ssl_key }}"
  notify: Restart pveproxy
